# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-18 07:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='urls',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='content_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='content_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_az',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_kz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_tr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_az',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_kz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_tr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430'),
        ),
    ]
