# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161123_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='text_kg',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
