# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161123_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description_ky',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='text_ky',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_ky',
            new_name='title_ru',
        ),
    ]
